# Generated by Django 4.2.3 on 2023-08-02 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20, null=True)),
                ('image', models.ImageField(upload_to='clinics')),
            ],
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='image',
        ),
        migrations.AddField(
            model_name='clinic',
            name='end',
            field=models.CharField(choices=[('8:00am', '8:00am'), ('9:00am', '9:00am'), ('10:00am', '10:00am'), ('11:00am', '11:00am'), ('12:00pm', '12:00pm'), ('1:00pm', '1:00pm'), ('2:00pm', '2:00pm'), ('3:00pm', '3:00pm'), ('4:00pm', '4:00pm'), ('5:00pm', '5:00pm'), ('6:00pm', '6:00pm')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='start',
            field=models.CharField(choices=[('8:00am', '8:00am'), ('9:00am', '9:00am'), ('10:00am', '10:00am'), ('11:00am', '11:00am'), ('12:00pm', '12:00pm'), ('1:00pm', '1:00pm'), ('2:00pm', '2:00pm'), ('3:00pm', '3:00pm'), ('4:00pm', '4:00pm'), ('5:00pm', '5:00pm'), ('6:00pm', '6:00pm')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.clinicday'),
        ),
    ]
