# Generated by Django 4.2.3 on 2023-08-02 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_clinicday_remove_clinic_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloader', models.FileField(null=True, upload_to='products')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.service')),
            ],
        ),
    ]
