# Generated by Django 4.2.3 on 2023-08-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
