# Generated by Django 4.2.3 on 2023-08-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_partner_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
