# Generated by Django 4.2.3 on 2023-08-03 07:10

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_partner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('requirements', tinymce.models.HTMLField()),
                ('summary', tinymce.models.HTMLField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], max_length=20)),
            ],
        ),
    ]
