# Generated by Django 4.2.3 on 2023-08-03 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
